# https://github.com/nalgeon/podsearch-py/tree/main/.github/workflows
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]

    env:
      USING_COVERAGE: "3.9"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions pytest black coverage

      - name: Run tox
        run: |
          make tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: contains(env.USING_COVERAGE, matrix.python-version)
        with:
          fail_ci_if_error: true
